version: '3.1'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=task
      - POSTGRES_USER=task
      - POSTGRES_DB=taskdb
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  demo-task-manager-service:
    build: .
    links:
      - postgres
    environment:
      SERVER.HOST: 0.0.0.0
      SERVER.PORT: 8080
      PG.USER: task
      PG.PASSWORD: task
      PG.HOST: postgres
      PG.PORT: 5432
      PG.DBNAME: taskdb
      PG.POOL.MAX_SIZE: 30
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
    ports:
      - 8080:8080
