version: '3.1'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=task
      - POSTGRES_USER=task
      - POSTGRES_DB=taskdb
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'

